name: main Build

# 리드미 수정 중 잠시 중지
#on:
#  push:
#    branches:
#      - main  # main브랜치 push할 이벤트 발생

jobs:
  build:
    runs-on: ubuntu-latest # ubuntu 최신 버전에서 구동
    steps:

      - name: Checkout source code. # repository에 있는 소스 코드를 체크아웃
        uses: actions/checkout@v2


      - name: Cache node modules # 노드를 설치 (package-lock.json에 있는 정보들도 같이 빌드)
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
            

      - name: Install Dependencies # 의존성 패키지 설치
        run: npm install


      - name: Build # 프로젝트 빌드    
        run: npm run build


      - name: Deploy # S3에 배포
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_S3_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_S3_SECRET_ACCESS_KEY_ID }}
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            dist s3://yongjun-store-web-page
